[package]
name    = "oxc_napi_resolver"
version = "0.0.0"
publish = false

[lib]
crate-type = ["cdylib"]
test       = false
doctest    = false

[dependencies]
oxc_resolver = { path = "../../oxc_resolver" }
napi         = { version = "2", default-features = false, features = ["napi3", "serde-json"] }
napi-derive  = { version = "2" }

[build-dependencies]
napi-build = "2"

[package.metadata.cargo-machete]
ignored = ["napi"]
